try
{
    var i = 2;
    var j = 0;
    var k = i/c;
}
catch(e)
{
    println("Oh! An error");
    println(e);
}

try
{
    var i = 9/0;
}

println('After try without catch');

try
{
    throw('Custom error');
}
catch(e)
{
    println("Oh! Another error");
    println(e);
}